/// <mls shortName="designSystem" project="102009" enhancement="_100554_enhancementLit" groupName="other" />

import { IDesignSystemTokens } from './_100554_designSystemBase'; 

export const tokens: IDesignSystemTokens[] = [

{
    "themeName": "Default",
    "description": "petshop",
    "color": {
        "color-primary": "#1C91CD",
        "color-secondary": "#F9B233",
        "color-accent": "#F97C2E",
        "color-background": "#ffffff",
        "color-surface": "#F9FAFB",
        "color-text-normal": "#403f3f",
        "color-text-secondary": "#6B6B6B",
        "color-text-disabled": "#B0B8C4",
        "color-border": "#E6E6E6",
        "color-link-normal": "#1C91CD",
        "color-link-hover": "#F97C2E",
        "color-link-visited": "#0F6FA9",
        "color-overlay": "rgba(28,145,205,0.08)",
        "color-error": "#FF4D4F",
        "color-warning": "#FAAD14",
        "color-success": "#52C41A",
        "_dark-color-primary": "#56a8d1",
        "_dark-color-secondary": "#F9B233",
        "_dark-color-accent": "#F97C2E",
        "_dark-color-background": "#0d1117",
        "_dark-color-surface": "#161b22",
        "_dark-color-text-normal": "#e6edf3",
        "_dark-color-text-secondary": "#b0b8c4",
        "_dark-color-text-disabled": "#636363",
        "_dark-color-border": "#262626",
        "_dark-color-link-normal": "#56a8d1",
        "_dark-color-link-hover": "#F97C2E",
        "_dark-color-link-visited": "#bddef3",
        "_dark-color-overlay": "rgba(86,168,209,0.12)",
        "_dark-color-error": "#f9676a",
        "_dark-color-warning": "#eead2b",
        "_dark-color-success": "#63d42b"
    },
    "global": {
        "spacing-xxs": "0.25rem",
        "spacing-xs": "0.5rem",
        "spacing-sm": "1rem",
        "spacing-md": "1.5rem",
        "spacing-lg": "2rem",
        "spacing-xl": "3rem",
        "spacing-xxl": "4rem",
        "border-radius-xs": "0.25rem",
        "border-radius-sm": "0.5rem",
        "border-radius-md": "1rem",
        "border-radius-lg": "2rem",
        "shadow-sm": "0 1px 4px rgba(28,145,205,0.08)",
        "shadow-md": "0 2px 8px rgba(28,145,205,0.12)",
        "shadow-lg": "0 4px 16px rgba(28,145,205,0.16)",
        "transition-base": "all 0.3s cubic-bezier(0.4,0,0.2,1)",
        "transition-fast": "all 0.15s cubic-bezier(0.4,0,0.2,1)",
        "transition-slow": "all 0.5s cubic-bezier(0.4,0,0.2,1)",
        "z-index-modal": "1000",
        "z-index-tooltip": "1100",
        "z-index-dropdown": "1200"
    },
    "typography": {
        "font-family-primary": "'Poppins', 'Charlie Display', Arial, sans-serif",
        "font-family-secondary": "serif",
        "font-size-xs": "0.75rem",
        "font-size-sm": "0.875rem",
        "font-size-md": "1rem",
        "font-size-lg": "1.25rem",
        "font-size-xl": "1.5rem",
        "font-size-xxl": "2rem",
        "font-weight-light": "300",
        "font-weight-normal": "400",
        "font-weight-bold": "700",
        "line-height-xs": "1.1",
        "line-height-sm": "1.3",
        "line-height-md": "1.5",
        "line-height-lg": "1.7"
    }
},

{
    "themeName": "Natal",
    "description": "Tema utilizado para o natal",
    "color": {
        "text-primary-color-lighter": "#D32F2F",
        "text-primary-color-lighter-hover": "#E53935",
        "text-primary-color-lighter-focus": "#C62828",
        "text-primary-color-lighter-disabled": "#B71C1C",
        "text-primary-color": "#FF0000",
        "text-primary-color-hover": "#FF4D4D",
        "text-primary-color-focus": "#E60000",
        "text-primary-color-disabled": "#FF9999",
        "text-primary-color-darker": "#8B0000",
        "text-primary-color-darker-hover": "#9B111E",
        "text-primary-color-darker-focus": "#7A0000",
        "text-primary-color-darker-disabled": "#660000",
        "text-secondary-color-lighter": "#4CAF50",
        "text-secondary-color-lighter-hover": "#66BB6A",
        "text-secondary-color-lighter-focus": "#43A047",
        "text-secondary-color-lighter-disabled": "#2E7D32",
        "text-secondary-color": "#008000",
        "text-secondary-color-hover": "#009933",
        "text-secondary-color-focus": "#006600",
        "text-secondary-color-disabled": "#339966",
        "text-secondary-color-darker": "#006400",
        "text-secondary-color-darker-hover": "#007700",
        "text-secondary-color-darker-focus": "#004d00",
        "text-secondary-color-darker-disabled": "#003300",
        "bg-primary-color-lighter": "#FFF5E1",
        "bg-primary-color-lighter-hover": "#FFEDD5",
        "bg-primary-color-lighter-focus": "#FFE4C4",
        "bg-primary-color-lighter-disabled": "#FFDAB9",
        "bg-primary-color": "#FFFFFF",
        "bg-primary-color-hover": "#F8F8F8",
        "bg-primary-color-focus": "#F0F0F0",
        "bg-primary-color-disabled": "#E0E0E0",
        "bg-primary-color-darker": "#F5F5DC",
        "bg-primary-color-darker-hover": "#EDE5C4",
        "bg-primary-color-darker-focus": "#DCD0A4",
        "bg-primary-color-darker-disabled": "#CDBE90",
        "bg-secondary-color-lighter": "#C5E1A5",
        "bg-secondary-color-lighter-hover": "#AED581",
        "bg-secondary-color-lighter-focus": "#9CCC65",
        "bg-secondary-color-lighter-disabled": "#8BC34A",
        "bg-secondary-color": "#4CAF50",
        "bg-secondary-color-hover": "#43A047",
        "bg-secondary-color-focus": "#388E3C",
        "bg-secondary-color-disabled": "#2E7D32",
        "bg-secondary-color-darker": "#1B5E20",
        "bg-secondary-color-darker-hover": "#2E7D32",
        "bg-secondary-color-darker-focus": "#388E3C",
        "bg-secondary-color-darker-disabled": "#4CAF50",
        "error-color": "#D32F2F",
        "error-color-hover": "#E57373",
        "error-color-focus": "#C62828",
        "error-color-disabled": "#B71C1C",
        "success-color": "#388E3C",
        "success-color-hover": "#4CAF50",
        "success-color-focus": "#2E7D32",
        "success-color-disabled": "#1B5E20",
        "warning-color": "#FFD700",
        "warning-color-hover": "#FFEA00",
        "warning-color-focus": "#FFC107",
        "warning-color-disabled": "#FFEB3B",
        "info-color": "#1565C0",
        "info-color-hover": "#1976D2",
        "info-color-focus": "#0D47A1",
        "info-color-disabled": "#64B5F6",
        "active-color": "#D32F2F",
        "active-color-hover": "#E53935",
        "active-color-focus": "#C62828",
        "active-color-disabled": "#B71C1C",
        "link-color": "#B22222",
        "link-color-hover": "#C71585",
        "link-color-focus": "#8B0000",
        "link-color-disabled": "#DC143C"
    },
    "global": {
        "breakpoint-small": "544px",
        "breakpoint-medium": "768px",
        "breakpoint-large": "1012px",
        "transition-slow": "0.2s",
        "transition-normal": "0.3s",
        "transition-fast": "0.5s",
        "space-base-unit": "0.25rem",
        "space-8": "calc(@space-base-unit * 2)",
        "space-16": "calc(@space-base-unit * 4)",
        "space-24": "calc(@space-base-unit * 6)",
        "space-32": "calc(@space-base-unit * 8)",
        "space-40": "calc(@space-base-unit * 10)",
        "space-48": "calc(@space-base-unit * 12)",
        "space-64": "calc(@space-base-unit * 16)"
    },
    "typography": {
        "font-base-unit": ".25rem",
        "font-family-primary": "'Charlie Display', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif",
        "font-family-secondary": "serif",
        "font-size-12": "calc(@font-base-unit * 3)",
        "font-size-16": "calc(@font-base-unit * 4)",
        "font-size-20": "calc(@font-base-unit * 5)",
        "font-size-24": "calc(@font-base-unit * 6)",
        "font-size-40": "calc(@font-base-unit * 10)",
        "font-size-48": "calc(@font-base-unit * 12)",
        "font-size-64": "calc(@font-base-unit * 16)",
        "line-height-base-unit": "1",
        "line-height-small": "calc(@line-height-base-unit * 1.1)",
        "line-height-medium": "calc(@line-height-base-unit * 1.3)",
        "line-height-large": "calc(@line-height-base-unit * 1.5)",
        "font-weight-lighter": "100",
        "font-weight-light": "200",
        "font-weight-normal": "400",
        "font-weight-bold": "700",
        "font-weight-bolder": "900"
    }
}

]
